import { copyFile, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { run } from './collect';
import { ensureBannerInReadme } from './readme-edit';

export async function commitBanner(args: {
  owner: string;
  name: string;
  pngPath: string;
  workdir: string;
  dryRun: boolean;
}): Promise<{ repo: string; action: 'pr-opened' | 'skipped' | 'dry-run' }> {
  const { owner, name, pngPath, workdir, dryRun } = args;
  const repo = `${owner}/${name}`;
  const dir = join(workdir, name);

  if (dryRun) {
    console.log(`[dry-run] would open PR on ${repo} with .github/banner.png`);
    return { repo, action: 'dry-run' };
  }

  await run(['gh', 'repo', 'clone', repo, dir, '--', '--depth', '1']);
  await mkdir(join(dir, '.github'), { recursive: true });
  await copyFile(pngPath, join(dir, '.github', 'banner.png'));

  const readmePath = join(dir, 'README.md');
  let readme = '';
  try {
    readme = await readFile(readmePath, 'utf8');
  } catch {
    readme = `# ${name}\n`;
  }
  const { content, changed } = ensureBannerInReadme(readme, name);
  if (changed) await writeFile(readmePath, content);

  await run(['git', '-C', dir, 'checkout', '-b', 'chore/readme-banner']);
  await run(['git', '-C', dir, 'add', '.github/banner.png', 'README.md']);
  await run(['git', '-C', dir, 'commit', '-m', 'chore: add branded README banner']);
  await run(['git', '-C', dir, 'push', '-u', 'origin', 'chore/readme-banner']);
  await run([
    'gh', 'pr', 'create', '-R', repo, '--head', 'chore/readme-banner',
    '--title', 'chore: add branded README banner',
    '--body', 'Adds `.github/banner.png` (generated by og-engine) and references it at the top of the README.',
  ]);

  return { repo, action: 'pr-opened' };
}
