import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { run } from './collect';
import { ensureBannerInReadme } from './readme-edit';

/**
 * Runs a git command and reports whether it produced a non-zero exit code,
 * without throwing. Used for status checks (e.g. `git diff --cached --quiet`)
 * where a non-zero exit is an expected outcome, not a failure.
 */
async function runStatus(cmd: string[]): Promise<number> {
  const proc = Bun.spawn(cmd, { stdout: 'ignore', stderr: 'ignore' });
  return proc.exited;
}

async function hasStagedChanges(dir: string): Promise<boolean> {
  // `git diff --cached --quiet` exits 0 when nothing is staged, 1 when something is.
  const code = await runStatus(['git', '-C', dir, 'diff', '--cached', '--quiet']);
  return code !== 0;
}

export async function commitBanner(args: {
  owner: string;
  name: string;
  pngPath: string;
  workdir: string;
  dryRun: boolean;
  noPr?: boolean;
}): Promise<{ repo: string; action: 'pr-opened' | 'pushed' | 'skipped' | 'dry-run' }> {
  const { owner, name, pngPath, workdir, dryRun, noPr = false } = args;
  const repo = `${owner}/${name}`;
  const dir = join(workdir, name);

  if (dryRun) {
    const how = noPr ? 'commit directly to the default branch of' : 'open PR on';
    console.log(`[dry-run] would ${how} ${repo} with .github/banner.png`);
    return { repo, action: 'dry-run' };
  }

  // Resumable: a prior run may have left a partial (or fully-cloned) checkout
  // behind, and `gh repo clone` refuses to clone into a non-empty directory.
  await rm(dir, { recursive: true, force: true });
  await run(['gh', 'repo', 'clone', repo, dir, '--', '--depth', '1']);
  await mkdir(join(dir, '.github'), { recursive: true });
  await copyFile(pngPath, join(dir, '.github', 'banner.png'));

  const readmePath = join(dir, 'README.md');
  let readme = '';
  try {
    readme = await readFile(readmePath, 'utf8');
  } catch {
    readme = `# ${name}\n`;
  }
  const { content, changed } = ensureBannerInReadme(readme, name);
  if (changed) await writeFile(readmePath, content);

  // --no-pr commits straight onto the cloned default branch; the PR flow needs
  // its own branch.
  if (!noPr) await run(['git', '-C', dir, 'checkout', '-b', 'chore/readme-banner']);
  await run(['git', '-C', dir, 'add', '.github/banner.png', 'README.md']);

  if (!(await hasStagedChanges(dir))) {
    // Banner + README are already up to date on this repo (e.g. a previous
    // run's PR already merged) — nothing to commit, so skip cleanly instead
    // of letting `git commit` hard-fail on an empty diff.
    return { repo, action: 'skipped' };
  }

  await run(['git', '-C', dir, 'commit', '-m', 'chore: add branded README banner']);

  if (noPr) {
    // Push the commit straight to the repo's default branch — no PR.
    await run(['git', '-C', dir, 'push', 'origin', 'HEAD']);
    return { repo, action: 'pushed' };
  }

  await run(['git', '-C', dir, 'push', '-u', 'origin', 'chore/readme-banner']);
  await run([
    'gh', 'pr', 'create', '-R', repo, '--head', 'chore/readme-banner',
    '--title', 'chore: add branded README banner',
    '--body', 'Adds `.github/banner.png` (generated by og-engine) and references it at the top of the README.',
  ]);

  return { repo, action: 'pr-opened' };
}
